name: build release

on:
  push:

jobs:
  build:
    name: psOff log analyser build
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Detect MSVC (Windows)
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x86_64

      - name: Configure
        run: |
          echo "::add-matcher::.github/matchers/cmake.json"
          cmake -S. -Bbuild/ -GNinja -DCMAKE_BUILD_TYPE=RelWithDebInfo

      - name: Build
        run: |
          echo "::add-matcher::.github/matchers/cmake.json"
          echo "::add-matcher::.github/matchers/compilers.json"
          cmake --build build/ -j4

      - name: Install
        run: |
          echo "::add-matcher::.github/matchers/cmake.json"
          cmake --install build/ --prefix build/.install/

      - name: Build release artifacts
        uses: actions/upload-artifact@v4
        with:
          name: psOff_logan
          path: |
            build/.install/*
